name: 'enpal_assessment_project'
version: '1.0.0'
profile: 'enpal_assessment_project'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  enpal_assessment_project:
    +schema: pipedrive_analytics
    +materialized: view
    
    staging:
      +materialized: view
      

    marts:
      +materialized: table
      core:
        fct_deal_funnel_events:
          +post-hook: "create unique index if not exists idx_fct_deal_step_fingerprint on {{ this }} (deal_step_fingerprint);"
