enpal_assessment_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 15432
      user: admin
      password: admin
      dbname: postgres
      schema: public
      threads: 1
      keepalives_idle: 0
